name: Generate Snake Animation

on:
  # Evento que dispara a animação
  schedule:
    - cron: "0 0 * * *" # Atualiza uma vez por dia
  workflow_dispatch: # Permite iniciar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Kayky-007
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          keep_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

